SCENARIOS = {
    'buy-pen': {
        'id': 'buy-pen',
        'title': 'Buy a pen from a shop',
        'situation_text': 'You need a pen to write your exam. You walk into a stationery shop. The shopkeeper looks up and smiles at you.',
        'situation_malayalam': 'Exam ezhuthaan oru pen venam. Ningal oru stationery shop-il kadakkukaanu. Shopkeeper ningale nokki chirikkunnu.',
        'mode': 'daily',
        'difficulty': 'beginner',
        'ai_persona': 'friendly shopkeeper',
        'ai_persona_description': 'A warm, patient shopkeeper at a small stationery shop. You speak clear, simple English and are happy to help students.',
        'starter_message': 'Hello! Welcome. How can I help you today?',
        'icon': '🖊️',
    },
    'ask-directions': {
        'id': 'ask-directions',
        'title': 'Ask for directions to the bus stop',
        'situation_text': 'You are new to an area and need to find the nearest bus stop. You spot a friendly-looking person standing on the street.',
        'situation_malayalam': 'Ningal oru puthiya sthalam-aanu. Bus stop evidev aano ennariyilla. Oru vyakthiye kaanunnu.',
        'mode': 'daily',
        'difficulty': 'beginner',
        'ai_persona': 'helpful local person',
        'ai_persona_description': 'A friendly local person who knows the area well and is happy to give directions.',
        'starter_message': 'Hi there! You look a bit lost. Can I help you with something?',
        'icon': '🗺️',
    },
    'order-food': {
        'id': 'order-food',
        'title': 'Order food at a restaurant',
        'situation_text': 'You sit down at a small restaurant for lunch. The waiter approaches your table with a menu.',
        'situation_malayalam': 'Ningal oru restaurant-il lunch kazhikkan irikunnu. Waiter menu theeyunnu.',
        'mode': 'daily',
        'difficulty': 'beginner',
        'ai_persona': 'restaurant waiter',
        'ai_persona_description': 'A professional, polite restaurant waiter who takes orders clearly and helpfully.',
        'starter_message': 'Good afternoon! Welcome to our restaurant. Are you ready to order, or would you like a few more minutes with the menu?',
        'icon': '🍽️',
    },
    'apologize-late': {
        'id': 'apologize-late',
        'title': 'Apologize for being late to class',
        'situation_text': 'You arrive 15 minutes late to your morning class. As you push open the classroom door, your teacher stops and looks at you.',
        'situation_malayalam': 'Ningal 15 minute late ayi class-il ethunnu. Teacher ningale nokkukaanu.',
        'mode': 'daily',
        'difficulty': 'beginner',
        'ai_persona': 'strict but fair college teacher',
        'ai_persona_description': 'A teacher who is firm but listens to polite apologies and genuine explanations.',
        'starter_message': "You're late again. The class started 15 minutes ago. What do you have to say for yourself?",
        'icon': '🕐',
    },
    'borrow-notes': {
        'id': 'borrow-notes',
        'title': "Ask to borrow a classmate's notes",
        'situation_text': 'You missed yesterday\'s class and need the notes before tomorrow\'s exam. You see your classmate in the library.',
        'situation_malayalam': 'Ningal naalthe class miss cheyhthu. Exam-nnu munpe notes venam. Library-l classmate-ne kaanunnu.',
        'mode': 'daily',
        'difficulty': 'beginner',
        'ai_persona': 'friendly classmate',
        'ai_persona_description': 'A helpful, friendly classmate who is studying in the library.',
        'starter_message': "Hey! Studying for tomorrow's exam too?",
        'icon': '📓',
    },
    'doctor-appointment': {
        'id': 'doctor-appointment',
        'title': 'Call a clinic to book an appointment',
        'situation_text': 'You have been feeling unwell and need to see a doctor. You call the local clinic to book an appointment for tomorrow.',
        'situation_malayalam': 'Ningalkku vendatha feel aakkunnu. Naalae doctor-ne kaanan clinic-il call cheyyunnu.',
        'mode': 'daily',
        'difficulty': 'intermediate',
        'ai_persona': 'clinic receptionist',
        'ai_persona_description': 'A professional, helpful clinic receptionist who schedules appointments over the phone.',
        'starter_message': 'Good morning, City Medical Clinic. How may I assist you today?',
        'icon': '📞',
    },
    'polite-complaint': {
        'id': 'polite-complaint',
        'title': 'Complain politely about a broken item',
        'situation_text': "You bought a pen yesterday from this shop but the cap is broken. You return to the shop politely to get it exchanged.",
        'situation_malayalam': 'Ningal innale vaangi pen-nte cap poyi. Ningal politely shop-il thirike pokunnu.',
        'mode': 'daily',
        'difficulty': 'intermediate',
        'ai_persona': 'slightly defensive shopkeeper',
        'ai_persona_description': 'A shopkeeper who is initially cautious about returns but responds well to polite, clear complaints.',
        'starter_message': 'Oh, you were in yesterday! Back again? What can I do for you?',
        'icon': '🛒',
    },
    'self-intro': {
        'id': 'self-intro',
        'title': 'Introduce yourself in an interview',
        'situation_text': 'You are sitting in a campus placement interview. The HR manager smiles and asks you to begin.',
        'situation_malayalam': 'Ningal campus placement interview-il aanu. HR manager ningale introduce cheyyaan parayunnu.',
        'mode': 'interview',
        'difficulty': 'intermediate',
        'ai_persona': 'HR interviewer',
        'ai_persona_description': 'A professional, attentive HR manager conducting a campus placement interview. You listen carefully and ask follow-up questions.',
        'starter_message': "Good morning! Please take a seat and make yourself comfortable. So, to start us off — could you tell me a little about yourself?",
        'icon': '👔',
    },
    'strengths-weaknesses': {
        'id': 'strengths-weaknesses',
        'title': 'Strengths and weaknesses question',
        'situation_text': 'The interviewer has moved past your introduction and now wants to know more about you.',
        'situation_malayalam': 'Interviewer ningalude strengths, weaknesses chodyikkunnu. Honest aay parayuka.',
        'mode': 'interview',
        'difficulty': 'intermediate',
        'ai_persona': 'HR interviewer',
        'ai_persona_description': 'A senior HR professional who values honest, thoughtful, specific answers — not rehearsed-sounding ones.',
        'starter_message': "That's a great background. Now, I'd like to understand you better — what would you say are your main strengths? And is there an area you're actively working to improve?",
        'icon': '💼',
    },
    'five-years': {
        'id': 'five-years',
        'title': 'Where do you see yourself in 5 years?',
        'situation_text': 'The interview is going well. The interviewer leans forward and asks about your future plans.',
        'situation_malayalam': 'Interview nallavannam pokukaanu. Interviewer ningalude future plans chodyikkunnu.',
        'mode': 'interview',
        'difficulty': 'advanced',
        'ai_persona': 'senior interviewer',
        'ai_persona_description': 'A senior interviewer who is evaluating whether the candidate has genuine ambition and a realistic plan.',
        'starter_message': "I appreciate your honesty. Let me ask you something many candidates find tricky — where do you see yourself five years from now, both personally and professionally?",
        'icon': '🎯',
    },
}

DAILY_SCENARIOS = [s for s in SCENARIOS.values() if s['mode'] == 'daily']
INTERVIEW_SCENARIOS = [s for s in SCENARIOS.values() if s['mode'] == 'interview']

DIFFICULTY_ORDER = {'beginner': 0, 'intermediate': 1, 'advanced': 2}
DAILY_SCENARIOS.sort(key=lambda s: DIFFICULTY_ORDER.get(s['difficulty'], 0))
INTERVIEW_SCENARIOS.sort(key=lambda s: DIFFICULTY_ORDER.get(s['difficulty'], 0))
